language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Soboleva_labs
  - make -j
  - ./TreeTabTest/TreeTabTest
notifications:
  email: false
